# Generated by Django 2.1.5 on 2019-02-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_text',
            field=models.TextField(),
        ),
    ]
