# Generated by Django 2.1.5 on 2019-02-18 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190217_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='suggestion_title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='suggestion',
            old_name='suggestion_text',
            new_name='suggestion',
        ),
    ]
