# Generated by Django 2.0.13 on 2019-04-16 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20190415_2018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(default='http://calgarypma.ca/wp-content/uploads/2018/01/default-thumbnail.jpg', upload_to=''),
        ),
    ]
