# Generated by Django 2.0.13 on 2019-04-16 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20190415_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='image',
        ),
        migrations.AddField(
            model_name='topic',
            name='imageURL',
            field=models.URLField(default='http://calgarypma.ca/wp-content/uploads/2018/01/default-thumbnail.jpg'),
        ),
    ]
