# Generated by Django 2.0.13 on 2019-04-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20190415_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='imageURL',
            field=models.URLField(default='https://assets.simplecast.com/assets/fallback/default-b7824fcd998f51baf0f0af359a72e760.png'),
        ),
    ]
