# Generated by Django 2.0.13 on 2019-04-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_topic_posturl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='postURL',
            field=models.CharField(default='#', max_length=50),
        ),
    ]
