# Generated by Django 2.0.13 on 2019-04-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20190416_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='imageURL',
        ),
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(default='default-thumbnail.jpg', upload_to=''),
        ),
    ]
