# Generated by Django 2.0.13 on 2019-04-16 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20190416_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(default='media/default-thumbnail.jpg', upload_to=''),
        ),
    ]
