# Generated by Django 2.0.13 on 2019-04-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20190416_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='image',
        ),
        migrations.AddField(
            model_name='topic',
            name='icon',
            field=models.CharField(default='<i class="fas fa-terminal"></i>', max_length=200),
        ),
    ]
